language: node_js
node_js:
  - "5"
install:
  - npm install
before_script:
  - npm run build
after_success:
  - git clone https://github.com/likr/opendap-viewer.git --branch=gh-pages tmp
  - npm run build
  - cp -R public/* tmp
  - pushd tmp
  - git add -A
  - git commit -m 'update'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/likr/opendap-viewer.git gh-pages 2> /dev/null'
  - popd
env:
  global:
    - GIT_COMMITTER_NAME: 'Yosuke ONOUE'
    - GIT_COMMITTER_EMAIL: 'onoue@likr-lab.com'
    - GIT_AUTHOR_NAME: 'Yosuke ONOUE'
    - GIT_AUTHOR_EMAIL: 'onoue@likr-lab.com'
    - secure: "W16msMnsck9hmWcxxXKaYy3+Wx3/w3qsfGmROM3CA7qlSTTy6UvqirdKUVl8aY6W825TGHW17hmLMG1FMSZd6IFCIYZ9rKy4kiNo3KsoaLgCOuC+R8VivFSASnFR9u1Z7G5zjf8ViuSz01U7GYe4Ypq49O0SKcHt22SyCKlNr6s="
